name: flutter_local_notifications
description: A cross platform plugin for displaying and scheduling local notifications for Flutter applications with the ability to customise for each platform.
version: 3.0.3
homepage: https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications
publish_to: none

dependencies:
  flutter:
    sdk: flutter
  platform: ">=2.12.0 <4.0.0"
  flutter_local_notifications_platform_interface: 
    path: ../flutter_local_notifications_platform_interface
  timezone: ^0.8.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^5.0.9
  plugin_platform_interface: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.dexterous.flutterlocalnotifications
        pluginClass: FlutterLocalNotificationsPlugin
      ios:
        pluginClass: FlutterLocalNotificationsPlugin
      macos:
        pluginClass: FlutterLocalNotificationsPlugin


environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.12.13+hotfix.5"
